// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNk3O4Y80Nl04t73q1C55FMh1s4VHYSag',
    appId: '1:873168968455:web:5d0984de8f2baf5c4ac3a2',
    messagingSenderId: '873168968455',
    projectId: 'online-drive-a75ca',
    authDomain: 'online-drive-a75ca.firebaseapp.com',
    storageBucket: 'online-drive-a75ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe-tVyZ5PAm5ismbbCJS_UWgLerEFvpF4',
    appId: '1:873168968455:android:3dd038958151fb244ac3a2',
    messagingSenderId: '873168968455',
    projectId: 'online-drive-a75ca',
    storageBucket: 'online-drive-a75ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATycRz0pbty7nemwgleA_xpIZstHs-8Pk',
    appId: '1:873168968455:ios:882f506eb0288c3e4ac3a2',
    messagingSenderId: '873168968455',
    projectId: 'online-drive-a75ca',
    storageBucket: 'online-drive-a75ca.firebasestorage.app',
    iosBundleId: 'com.example.cloudinaryFileUpload',
  );
}
